### ISSUE TITLE
Sign In not working

### ISSUE THREAD

**Issue by qmaruf** [privly/privly-web#161]
Sign in is not working and showing ***No route matches [GET] "/apps/Login/new.html***
***users/sign_in*** is redirected to ***/apps/Login/new.html***, I haven't found any such page.

**Comment by smcgregor** [comment]
Did you use `git clone --recursive ...` when cloning this repository? It sounds like you don't have the privly-applications git submodule.

**Comment by qmaruf** [comment]
Yeah. It works now. You may add this info into the readme page.
