### ISSUE TITLE
Request has been blocked; the content must be served over HTTPS.

### ISSUE THREAD

**Issue by qmaruf** [privly/privly-web#166]
I get this error in browser console while clicking the lock icon in any textbox. 

> Mixed Content: The page at 'chrome-extension://pkokikcdapfpkkkjpdaamjanniaempol/privly-applications/Mes…269515202a434222&appid=posting.app.3550c95215202a231cca8ce269515202a434222' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/posts/user_account_data'. This request has been blocked; the content must be served over HTTPS.

![Request has been blocked; the content must be served over HTTPS.](http://i.imgur.com/5MiKII2.png)

**Comment by smcgregor** [comment]
Your content server is http://localhost:3000? Since localhost is not over SSL, seamless posting will not work on sites that implement a content security policy.

**Comment by qmaruf** [comment]
I suspected that too. Do you use any workaround? I found some resources to tackle this problem on localhost.

**Comment by smcgregor** [comment]
You don't get this problem [here](http://test.privly.org/test_pages/privly_button.html), do you?

**Comment by qmaruf** [comment]
Nope, works fine.

**Comment by smcgregor** [comment]
This only matters for developers, and it is more of an annoyance than a bug. I'd label this "won't fix" unless somebody has strong feelings about it.
